# Wave 1 within the external-secrets app — applied after the ESO Helm chart
# resources (wave 0 by default) so the CRD exists before we try to create
# a ClusterSecretStore instance.
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes/mgmt"
          role: "grafana"
          serviceAccountRef:
            name: prometheus-grafana
            namespace: observability