# Wave 2 — fires after the kube-prometheus-stack chart (wave 0) has created
# the prometheus-grafana ServiceAccount that the ClusterSecretStore uses for
# Vault Kubernetes auth. Without this ordering, ESO auth fails because the
# ServiceAccount doesn't exist yet when the ExternalSecret first reconciles.
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: secret/grafana
        property: admin-user
    - secretKey: admin-password
      remoteRef:
        key: secret/grafana
        property: admin-password